import {
  FaEnvelope,
  FaGithub,
  FaLinkedin,
  FaWhatsapp,
  FaReact,
  FaJs,
  FaHtml5,
  FaCss3Alt,
  FaNodeJs,
  FaGitAlt,
  FaGlobe,
} from "react-icons/fa";
import { SiExpress, SiMongodb, SiPostman, SiRedux, SiRender, SiTailwindcss, SiVercel } from "react-icons/si";
import { VscCode } from "react-icons/vsc";
import { MdOutlineCloudDone, MdOutlineDesignServices } from "react-icons/md";
import type { Project, Service, Skill } from "../types/portfolio";

export const profile = {
  name: "Mithun Talukdar",
  role: "AI-Powered Full Stack Developer",
  status: "Available for Opportunities",
  location: "Kolkata, West Bengal, India",
  email: "mithuntalukdar2003@gmail.com",
  phone: "+91 87776 73839",
  whatsappNumber: "918777673839",
  whatsappFormatted: "+91 87776 73839",
  whatsapp: "https://wa.me/918777673839",
  github: "https://github.com/MithunTalukdar",
  linkedin: "https://linkedin.com/in/mithun-talukdar",
  bio: "Specializing in building modern, scalable web applications with MERN Stack, Next.js, and AI Integration. Crafting robust REST APIs and high-performance, user-centric interfaces.",
  resume: "/Mithun-Talukdar-Resume.pdf",
};

export const navItems = [
  "Home",
  "About",
  "Education",
  "Skills",
  "Projects",
  "Experience",
  "Services",
  "GitHub",
  "Contact",
];

export const socialLinks = [
  { label: "WhatsApp", href: `https://wa.me/918777673839?text=${encodeURIComponent("Hi Mithun, I saw your portfolio and would like to connect!")}`, icon: FaWhatsapp },
  { label: "GitHub", href: profile.github, icon: FaGithub },
  { label: "LinkedIn", href: profile.linkedin, icon: FaLinkedin },
  { label: "Email", href: `mailto:${profile.email}`, icon: FaEnvelope },
];

export const aboutCards = [
  { label: "Education", value: "Bachelor Degree", detail: "Computer science foundation with software engineering focus." },
  { label: "Skills", value: "MERN Stack", detail: "React, Node, Express, MongoDB, APIs, auth, and deployment." },
  { label: "Experience", value: "Project Ready", detail: "Academic, full-stack, and business website delivery experience." },
  { label: "Career Goals", value: "Product Builder", detail: "Create scalable web products that solve practical business problems." },
];

export const education = {
  degree: "Bachelor Degree in Computer Science",
  institution: "Undergraduate Academic Program",
  period: "2026",
  summary:
    "Focused on practical software development, database-backed applications, modern web architecture, and deployment workflows.",
  coursework: ["Web Development", "Database Management", "Software Engineering", "Computer Networks"],
};

export const skills: Skill[] = [
  {
    name: "HTML5",
    level: 95,
    category: "Frontend",
    levelTier: "Master",
    brandColor: "#e34f26",
    glowColor: "rgba(227, 79, 38, 0.45)",
    accentGradient: "from-orange-500 to-red-600",
    tagline: "Semantic web architecture & SEO accessibility",
    keyConcepts: ["Semantic Tags", "Accessibility (a11y)", "Canvas & SVG", "Audio/Video APIs", "SEO Optimization"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "Swastik International", "Course Platform"],
    synergyWith: ["CSS3", "JavaScript ES6+", "React.js", "Tailwind CSS"],
  },
  {
    name: "CSS3",
    level: 92,
    category: "Frontend",
    levelTier: "Master",
    brandColor: "#264de4",
    glowColor: "rgba(38, 77, 228, 0.45)",
    accentGradient: "from-blue-600 to-indigo-600",
    tagline: "Modern responsive styling, flexbox & grid physics",
    keyConcepts: ["Flexbox & Grid", "CSS Custom Properties", "Keyframe Animations", "Glassmorphism", "Responsive Layouts"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "Swastik International", "Portfolio"],
    synergyWith: ["HTML5", "Tailwind CSS", "React.js"],
  },
  {
    name: "JavaScript ES6+",
    level: 90,
    category: "Frontend",
    levelTier: "Master",
    brandColor: "#f7df1e",
    glowColor: "rgba(247, 223, 30, 0.45)",
    accentGradient: "from-yellow-400 to-amber-500",
    tagline: "Asynchronous programming, closures & DOM mechanics",
    keyConcepts: ["Async/Await & Promises", "Closures & Prototypes", "ES6+ Modules", "DOM Manipulation", "Event Loop Physics"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "User Management Auth", "Course Platform"],
    synergyWith: ["React.js", "Node.js", "Express.js", "Redux"],
  },
  {
    name: "React.js",
    level: 88,
    category: "Frontend",
    levelTier: "Advanced",
    brandColor: "#00d8ff",
    glowColor: "rgba(0, 216, 255, 0.45)",
    accentGradient: "from-cyan-400 to-blue-500",
    tagline: "Component architectures, hooks & high-performance state",
    keyConcepts: ["Custom Hooks", "Context API", "Virtual DOM & Reconciliation", "Suspense & Lazy", "Framer Motion"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "Course Platform", "Swastik International", "Portfolio"],
    synergyWith: ["Redux", "React Router", "Tailwind CSS", "Node.js", "JavaScript ES6+"],
  },
  {
    name: "Tailwind CSS",
    level: 86,
    category: "Frontend",
    levelTier: "Advanced",
    brandColor: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.45)",
    accentGradient: "from-sky-400 to-teal-500",
    tagline: "Utility-first design systems & dark mode dynamics",
    keyConcepts: ["Custom Configurations", "Arbitrary Variants", "Dark Mode Theming", "Grid/Flex Layouts", "Performance Purging"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "Course Platform", "Portfolio"],
    synergyWith: ["React.js", "CSS3", "HTML5"],
  },
  {
    name: "Redux",
    level: 78,
    category: "Frontend",
    levelTier: "Proficient",
    brandColor: "#764abc",
    glowColor: "rgba(118, 74, 188, 0.45)",
    accentGradient: "from-purple-500 to-indigo-600",
    tagline: "Predictable global state management & async thunks",
    keyConcepts: ["Redux Toolkit (RTK)", "Slices & Reducers", "RTK Query", "Middleware & Thunks", "State Normalization"],
    projectsUsed: ["Lumina E-Commerce", "LMS Platform"],
    synergyWith: ["React.js", "JavaScript ES6+"],
  },
  {
    name: "React Router",
    level: 84,
    category: "Frontend",
    levelTier: "Advanced",
    brandColor: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.45)",
    accentGradient: "from-rose-500 to-pink-600",
    tagline: "Declarative SPA routing, nested routes & route guards",
    keyConcepts: ["Protected Routes", "Dynamic URL Params", "Nested Route Layouts", "Loaders & Actions", "Navigation Guards"],
    projectsUsed: ["LMS Platform", "Course Platform", "User Management Auth"],
    synergyWith: ["React.js", "JWT Authentication"],
  },
  {
    name: "Node.js",
    level: 84,
    category: "Backend",
    levelTier: "Advanced",
    brandColor: "#22c55e",
    glowColor: "rgba(34, 197, 94, 0.45)",
    accentGradient: "from-emerald-500 to-green-600",
    tagline: "Scalable server runtimes, event-driven micro-services",
    keyConcepts: ["Event Loop Architecture", "File System & Streams", "Buffer & Crypto Modules", "NPM Modules", "Process Management"],
    projectsUsed: ["LMS Backend API", "User Auth System", "HomePro Backend"],
    synergyWith: ["Express.js", "MongoDB Atlas", "REST APIs", "JWT Authentication"],
  },
  {
    name: "Express.js",
    level: 83,
    category: "Backend",
    levelTier: "Advanced",
    brandColor: "#cbd5e1",
    glowColor: "rgba(203, 213, 225, 0.45)",
    accentGradient: "from-slate-300 to-zinc-500",
    tagline: "Modular REST APIs, middleware pipelines & error handling",
    keyConcepts: ["Custom Middleware", "Router Separation", "Error Handling Pipelines", "CORS & Rate Limiting", "Input Validation"],
    projectsUsed: ["LMS Backend", "User Management API", "HomePro Backend"],
    synergyWith: ["Node.js", "Mongoose", "JWT Authentication", "REST APIs"],
  },
  {
    name: "REST APIs",
    level: 87,
    category: "Backend",
    levelTier: "Advanced",
    brandColor: "#3b82f6",
    glowColor: "rgba(59, 130, 246, 0.45)",
    accentGradient: "from-blue-500 to-cyan-600",
    tagline: "Resource-oriented HTTP architectures & secure endpoints",
    keyConcepts: ["CRUD Protocols", "HTTP Status Codes", "Payload Validation", "Pagination & Filtering", "API Documentation"],
    projectsUsed: ["LMS Platform", "Lumina E-Commerce", "User Management Auth", "Course Platform"],
    synergyWith: ["Node.js", "Express.js", "Postman"],
  },
  {
    name: "JWT Authentication",
    level: 82,
    category: "Backend",
    levelTier: "Advanced",
    brandColor: "#ec4899",
    glowColor: "rgba(236, 72, 153, 0.45)",
    accentGradient: "from-pink-500 to-rose-600",
    tagline: "Stateless security tokens, authorization & role guards",
    keyConcepts: ["Access & Refresh Tokens", "Bearer Auth Headers", "Role-Based Access Control (RBAC)", "Token Expiry Handling", "HttpOnly Cookies"],
    projectsUsed: ["LMS Platform", "User Management Auth System"],
    synergyWith: ["Bcrypt", "Node.js", "Express.js", "React Router"],
  },
  {
    name: "Bcrypt",
    level: 78,
    category: "Backend",
    levelTier: "Proficient",
    brandColor: "#a855f7",
    glowColor: "rgba(168, 85, 247, 0.45)",
    accentGradient: "from-purple-500 to-violet-600",
    tagline: "Salt-hashed password hashing & cryptographic safety",
    keyConcepts: ["Salt Rounds Tuning", "Async Password Hashing", "Constant-Time Verification", "Credential Protection", "Secure User Auth"],
    projectsUsed: ["LMS Platform", "User Management Auth System"],
    synergyWith: ["JWT Authentication", "Node.js", "Express.js"],
  },
  {
    name: "MongoDB Atlas",
    level: 84,
    category: "Database",
    levelTier: "Advanced",
    brandColor: "#10b981",
    glowColor: "rgba(16, 185, 129, 0.45)",
    accentGradient: "from-emerald-400 to-teal-600",
    tagline: "Cloud NoSQL clusters, aggregations & database indexes",
    keyConcepts: ["NoSQL Schemas", "Atlas Cloud Clusters", "Aggregation Pipelines", "Compound Indexing", "Connection Pooling"],
    projectsUsed: ["LMS Platform", "User Management Auth", "HomePro Backend"],
    synergyWith: ["Mongoose", "Node.js", "Express.js"],
  },
  {
    name: "Mongoose",
    level: 82,
    category: "Database",
    levelTier: "Advanced",
    brandColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.45)",
    accentGradient: "from-red-500 to-rose-700",
    tagline: "Strict ODM schemas, pre/post hooks & population",
    keyConcepts: ["Schema & Model Design", "Pre/Post Middleware Hooks", "Document Population", "Type Validation", "Virtuals & Methods"],
    projectsUsed: ["LMS Platform", "User Management Auth"],
    synergyWith: ["MongoDB Atlas", "Node.js", "Express.js"],
  },
  {
    name: "Git",
    level: 86,
    category: "Tools",
    levelTier: "Advanced",
    brandColor: "#f97316",
    glowColor: "rgba(249, 115, 22, 0.45)",
    accentGradient: "from-orange-500 to-amber-600",
    tagline: "Branching strategies, commit hygiene & version control",
    keyConcepts: ["Feature Branching", "Rebasing & Merging", "Stash & Cherry-pick", "Git Hooks", "Conflict Resolution"],
    projectsUsed: ["All Full Stack Projects", "Academic Repos"],
    synergyWith: ["GitHub", "VS Code"],
  },
  {
    name: "GitHub",
    level: 86,
    category: "Tools",
    levelTier: "Advanced",
    brandColor: "#c084fc",
    glowColor: "rgba(192, 132, 252, 0.45)",
    accentGradient: "from-purple-400 to-indigo-600",
    tagline: "Repository hosting, open-source workflow & releases",
    keyConcepts: ["Pull Requests & Reviews", "GitHub Actions CI/CD", "Issue Tracking", "Markdown Documentation", "Release Management"],
    projectsUsed: ["All 15+ Repositories", "LMS Project", "Lumina E-Commerce"],
    synergyWith: ["Git", "Vercel", "Render"],
  },
  {
    name: "Postman",
    level: 82,
    category: "Tools",
    levelTier: "Advanced",
    brandColor: "#fb923c",
    glowColor: "rgba(251, 146, 60, 0.45)",
    accentGradient: "from-orange-400 to-amber-600",
    tagline: "API automated testing, environments & mock payloads",
    keyConcepts: ["Collections & Environments", "Auth Token Injection", "Automated Assertions", "Payload Inspection", "Mock Servers"],
    projectsUsed: ["LMS REST APIs", "User Auth Endpoints"],
    synergyWith: ["REST APIs", "Express.js", "Node.js"],
  },
  {
    name: "VS Code",
    level: 90,
    category: "Tools",
    levelTier: "Master",
    brandColor: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.45)",
    accentGradient: "from-blue-400 to-cyan-500",
    tagline: "Custom productivity configurations & debugging workflows",
    keyConcepts: ["TypeScript Debugger", "ESLint & Prettier Setup", "Snippets & Emmet", "Integrated Terminal", "Git Lens Workflows"],
    projectsUsed: ["All Engineering Projects"],
    synergyWith: ["Git", "GitHub"],
  },
  {
    name: "Vercel",
    level: 82,
    category: "Tools",
    levelTier: "Advanced",
    brandColor: "#ffffff",
    glowColor: "rgba(255, 255, 255, 0.45)",
    accentGradient: "from-slate-200 to-zinc-400",
    tagline: "Edge frontend deployment, CI/CD previews & SSL delivery",
    keyConcepts: ["Edge Deployments", "Environment Variables", "Custom Domains", "Instant Previews", "Serverless Routes"],
    projectsUsed: ["LMS Frontend", "Lumina E-Commerce", "Course Platform", "Swastik"],
    synergyWith: ["React.js", "GitHub"],
  },
  {
    name: "Render",
    level: 78,
    category: "Tools",
    levelTier: "Proficient",
    brandColor: "#46e3b7",
    glowColor: "rgba(70, 227, 183, 0.45)",
    accentGradient: "from-emerald-400 to-teal-500",
    tagline: "Cloud web services, automatic branch deployments & logs",
    keyConcepts: ["Node.js Web Services", "Automatic Git Deployments", "Environment Secrets", "Live Health Monitoring", "Disk Storage"],
    projectsUsed: ["LMS Backend API", "User Auth Backend"],
    synergyWith: ["Node.js", "Express.js", "MongoDB Atlas"],
  },
];

export const skillOrbits = [
  {
    label: "Frontend Orbit",
    category: "Frontend",
    radius: 42,
    duration: 28,
    color: "cyan",
    skills: [
      { name: "React.js", icon: FaReact, detail: "Component-driven interfaces, hooks, routing, state, and production React patterns." },
      { name: "JavaScript", icon: FaJs, detail: "Modern ES6+ logic, async flows, DOM behavior, and application interactions." },
      { name: "HTML5", icon: FaHtml5, detail: "Semantic structure, accessibility-first markup, and clean document foundations." },
      { name: "CSS3", icon: FaCss3Alt, detail: "Responsive layouts, animation, visual systems, and polished interface styling." },
      { name: "Tailwind CSS", icon: SiTailwindcss, detail: "Utility-first design systems, fast iteration, and consistent responsive UI." },
      { name: "Redux", icon: SiRedux, detail: "Predictable state management for complex React application workflows." },
    ],
  },
  {
    label: "Backend Orbit",
    category: "Backend",
    radius: 32,
    duration: 34,
    color: "violet",
    skills: [
      { name: "Node.js", icon: FaNodeJs, detail: "Server-side JavaScript runtimes for scalable API and business logic." },
      { name: "Express.js", icon: SiExpress, detail: "Modular REST APIs, middleware, protected routes, and clean controllers." },
      { name: "REST API", icon: FaGlobe, detail: "Resource-oriented API design with reliable request and response flows." },
      { name: "JWT Authentication", icon: FaReact, detail: "Token-based authentication, authorization, and protected application areas." },
      { name: "Bcrypt", icon: SiMongodb, detail: "Secure password hashing and account credential protection." },
    ],
  },
  {
    label: "Database Orbit",
    category: "Database",
    radius: 24,
    duration: 38,
    color: "emerald",
    skills: [
      { name: "MongoDB", icon: SiMongodb, detail: "Document database design, collections, aggregation pipelines, and Atlas clusters." },
      { name: "Mongoose", icon: SiMongodb, detail: "Schema validation, business models, indexing, and transactional integrity." },
      { name: "MongoDB Atlas", icon: SiMongodb, detail: "Cloud-hosted database clusters, automated backups, and global scalability." },
    ],
  },
  {
    label: "Tools Orbit",
    category: "Tools",
    radius: 50,
    duration: 42,
    color: "amber",
    skills: [
      { name: "Git", icon: FaGitAlt, detail: "Version control workflows, branching, review-friendly commits, and collaboration." },
      { name: "GitHub", icon: FaGithub, detail: "Repository management, project hosting, collaboration, and portfolio proof." },
      { name: "VS Code", icon: VscCode, detail: "Efficient development environment with extensions and debugging workflows." },
      { name: "Postman", icon: SiPostman, detail: "API testing, request collections, auth checks, and integration validation." },
      { name: "Vercel", icon: SiVercel, detail: "Frontend deployment, previews, and optimized production hosting." },
      { name: "Render", icon: SiRender, detail: "Backend service hosting, environment configuration, and full-stack deployment." },
    ],
  },
] as const;

export const techWall = [
  { name: "React.js", icon: FaReact, accent: "from-cyan-300 to-sky-500" },
  { name: "Node.js", icon: FaNodeJs, accent: "from-emerald-300 to-lime-500" },
  { name: "MongoDB", icon: SiMongodb, accent: "from-green-300 to-emerald-600" },
  { name: "Express.js", icon: SiExpress, accent: "from-slate-200 to-slate-500" },
  { name: "Tailwind CSS", icon: SiTailwindcss, accent: "from-cyan-200 to-teal-500" },
  { name: "GitHub", icon: FaGithub, accent: "from-fuchsia-300 to-violet-600" },
];

export const projects: Project[] = [
  {
    title: "AMD IT SOLUTION (ADM Techno Solution)",
    slug: "amd-it-solution",
    description:
      "A comprehensive enterprise IT services and infrastructure portal in Kolkata providing 24/7 CCTV surveillance, computer and laptop hardware repair, corporate networking, and AMC contracts with rapid doorstep support.",
    features: [
      "On-Demand IT & CCTV Services",
      "Doorstep Hardware Diagnostics",
      "Enterprise AMC Contracts",
      "Emergency 24/7 Service Channels",
      "Automated WhatsApp & Direct Inquiries",
      "High-Performance Responsive Portal",
    ],
    tech: ["React.js", "Node.js", "Express.js", "Tailwind CSS", "REST APIs", "Vite"],
    categories: ["Full Stack", "Business"],
    gradient: "from-blue-600 via-indigo-600 to-cyan-500",
    liveUrl: "https://amd-tecno-solution.vercel.app",
    repoUrl: "https://github.com/MithunTalukdar/AMD-IT-SOLUTION",
  },
  {
    title: "Learning Management System (LMS)",
    slug: "lms",
    description:
      "A full-stack academic platform built using MERN Stack that enables students, instructors, and administrators to manage courses, track real-time learning progress, attempt quizzes, and issue verified completion certificates.",
    features: [
      "Role-Based Authentication (JWT)",
      "Course Curriculum Management",
      "Interactive Quiz Engine",
      "Real-Time Progress Tracking",
      "Automated Certificate Generation",
      "Admin Analytics Dashboard",
    ],
    tech: ["React.js", "Node.js", "Express.js", "MongoDB", "JWT Auth", "Tailwind CSS"],
    categories: ["Full Stack"],
    gradient: "from-cyan-500 via-blue-600 to-indigo-700",
    liveUrl: "https://lms-pi-six-31.vercel.app",
    repoUrl: "https://github.com/MithunTalukdar/LMS",
  },
  {
    title: "ResumeAI — AI Resume Builder & Career Studio",
    slug: "user-auth",
    description:
      "A full-stack AI career acceleration platform and user management system powered by AI. Features secure JWT authentication, OTP email verification, intelligent ATS resume generation, profile sync, and instant PDF/DOCX downloads.",
    features: [
      "Secure JWT Auth & OTP Email Verification",
      "AI-Powered ATS Resume Generator",
      "User Profile Cloud CRUD & Sync",
      "1-Click PDF & DOCX Document Export",
      "HR Summary & LinkedIn Optimizer",
      "RESTful API Architecture & MongoDB",
    ],
    tech: ["React.js", "Node.js", "Express.js", "MongoDB Atlas", "OpenAI API", "JWT Auth"],
    categories: ["Full Stack", "Business"],
    gradient: "from-blue-500 via-indigo-600 to-purple-700",
    liveUrl: "https://myjobmekar.vercel.app",
    repoUrl: "https://github.com/MithunTalukdar/User",
  },
  {
    title: "Lumina E-Commerce Shopping Platform",
    slug: "lumina",
    description:
      "A modern, full-featured online storefront with rapid product discovery, interactive category filters, real-time cart state management, checkout flows, and responsive mobile-first UI.",
    features: [
      "Dynamic Product Catalog",
      "Cart & State Persistence",
      "Instant Search & Category Filters",
      "Seamless Checkout Flow",
      "Mobile-Optimized Experience",
    ],
    tech: ["TypeScript", "React.js", "Tailwind CSS", "REST APIs", "Vite"],
    categories: ["Full Stack", "E-Commerce"],
    gradient: "from-emerald-500 via-teal-600 to-cyan-700",
    liveUrl: "https://lumina-shoping.vercel.app",
    repoUrl: "https://github.com/MithunTalukdar/lumina-shoping",
  },
  {
    title: "Course Learning Web Platform",
    slug: "course",
    description:
      "An interactive educational platform designed for seamless video course consumption, structured module navigation, progress indicators, and intuitive student dashboards.",
    features: [
      "Course Module Directory",
      "Video Player Integration",
      "Curriculum Outlines",
      "Responsive Learning View",
      "Student Dashboard UI",
    ],
    tech: ["React.js", "JavaScript", "Tailwind CSS", "REST APIs", "Vercel"],
    categories: ["Frontend"],
    gradient: "from-purple-500 via-violet-600 to-pink-600",
    liveUrl: "https://course-pi-navy.vercel.app/",
    repoUrl: "https://github.com/MithunTalukdar/course",
  },
  {
    title: "Swastik International Corporate Portal",
    slug: "swastik",
    description:
      "A premier business website designed for an international trade and consulting enterprise, featuring modern aesthetic layouts, company profile sections, and high-conversion client inquiry channels.",
    features: [
      "Company Profile Presentation",
      "Global Services Showcase",
      "Lead Capture & Contact Forms",
      "High-Performance Responsive Layout",
      "SEO & Accessibility Optimized",
    ],
    tech: ["React.js", "Tailwind CSS", "JavaScript ES6+", "Vercel"],
    categories: ["Frontend", "Business"],
    gradient: "from-amber-500 via-rose-600 to-purple-700",
    liveUrl: "https://swastik-international.vercel.app",
    repoUrl: "https://github.com/MithunTalukdar/Swastik-International",
  },
  {
    title: "HomePro Service Management",
    slug: "homepro",
    description:
      "A comprehensive full-stack service booking and technician management platform built with modern TypeScript and React for on-demand home maintenance requests.",
    features: [
      "On-Demand Service Catalog",
      "Service Booking Management",
      "Technician Dispatch & Tracking",
      "Role-Based Access Control",
    ],
    tech: ["TypeScript", "React.js", "Node.js", "Express.js", "MongoDB"],
    categories: ["Full Stack", "Business"],
    gradient: "from-cyan-500 via-teal-600 to-emerald-700",
    liveUrl: "https://github.com/MithunTalukdar/HomePro",
    repoUrl: "https://github.com/MithunTalukdar/HomePro",
  },
];

export const experience = [
  {
    title: "MERN Stack Development",
    detail: "Building end-to-end production web applications using MongoDB, Express.js, React.js, and Node.js.",
  },
  {
    title: "Frontend Engineering",
    detail: "Crafting highly responsive, accessible, and dynamic user interfaces using React, TypeScript, and Tailwind CSS.",
  },
  {
    title: "Backend API Architecture",
    detail: "Designing modular RESTful APIs, implementing JWT authentication, middleware pipelines, and Bcrypt security.",
  },
  {
    title: "Database Modeling",
    detail: "Structuring schema architectures, relationships, indexing, and Atlas cloud clusters in MongoDB.",
  },
  {
    title: "Production Deployment",
    detail: "Deploying and managing frontend client apps on Vercel and scalable backend services on Render.",
  },
];

export const services: Service[] = [
  {
    title: "Full Stack Web Development",
    description:
      "End-to-end custom web applications built with high scalability, type-safe code, and optimal performance.",
    icon: FaReact,
  },
  {
    title: "Responsive Frontend Design",
    description:
      "Clean, modern, and high-conversion UI/UX interfaces that render flawlessly on mobile, tablet, and desktop screens.",
    icon: MdOutlineDesignServices,
  },
  {
    title: "MERN Stack Applications",
    description:
      "Complete full-stack database-backed platforms utilizing MongoDB, Express.js, React.js, and Node.js.",
    icon: SiMongodb,
  },
  {
    title: "REST API Development",
    description:
      "Secure, scalable, and modular RESTful APIs with token-based JWT authentication and validation layers.",
    icon: FaGlobe,
  },
  {
    title: "Database Architecture",
    description:
      "Efficient schema modeling, indexing strategies, and database cluster management with MongoDB Atlas.",
    icon: SiMongodb,
  },
  {
    title: "Cloud Deployment & DevOps",
    description:
      "Continuous deployment workflows, domain routing, and production infrastructure management on Vercel and Render.",
    icon: MdOutlineCloudDone,
  },
];

export const achievements = [
  { value: 12, suffix: "+", label: "Projects Completed" },
  { value: 10, suffix: "", label: "Public Repositories" },
  { value: 20, suffix: "+", label: "Technologies Mastered" },
  { value: 1200, suffix: "+", label: "Hours of Coding" },
];
